[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Jstaller"
version = "1.0"
requires-python = ">= 3.8"
description = "Welcome to Jstaller , A easy-to-use installer platform based on self-extracceding archives"
